version: "3.9"

services:
  mysql:
    image: mysql:8.0.39
    container_name: ragflow-mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ragflow

  redis:
    image: redis:6.2
    container_name: ragflow-redis
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - ragflow

  minio:
    image: minio/minio
    container_name: ragflow-minio
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    networks:
      - ragflow

  infinity:    
    image: infiniflow/infinity:v0.6.0-dev3
    container_name: ragflow-infinity
    ports:
      - "23817:23817"
    environment:
      - MEM_LIMIT=4g
    networks:
      - ragflow

  ragflow:
    image: ${RAGFLOW_IMAGE}
    container_name: ragflow-server
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:15678"
      - "9380:9380"      
      - "9443:443"
      - "5678:5678"
      - "5679:5679"
      - "9382:9382"
    volumes:
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./entrypoint.sh:/ragflow/entrypoint.sh
      - ./embedding_models.yaml:/ragflow/conf/embedding_models.yaml
      - ./service_conf.yaml.template:/ragflow/conf/service_conf.yaml.template
      - ../history_data_agent:/ragflow/history_data_agent
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - OLLAMA_BASE_URL=http://ollama:11434
    networks:
      - ragflow
      - sitepilot 
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles: [infinity]
    mem_limit: 2500m # ⬅️ Set memory limit to 2.5GB

volumes:
  mysql_data:
  minio_data:
  ollama_data:

networks:
  ragflow:
    driver: bridge
  sitepilot:
    external: true